$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$headerPath = $env:NOOK_EMBEDDED_NCORE_HEADER_PATH
if ([string]::IsNullOrWhiteSpace($headerPath)) {
    $headerPath = Join-Path $repoRoot "server\\generated\\nook_embedded_ncore_blob.h"
}

$candidateSources = @(
    (Join-Path $repoRoot "libs\\arm64-v8a\\libncore.so"),
    (Join-Path $repoRoot "build\\libs\\arm64-v8a\\libncore.so"),
    (Join-Path $repoRoot "build\\single-server-package\\arm64-v8a\\libncore.so"),
    (Join-Path $repoRoot "build\\single-server-staging\\arm64-v8a\\libncore.so"),
    (Join-Path $repoRoot "obj\\local\\arm64-v8a\\libncore.so"),
    (Join-Path $repoRoot "build\\android\\libs\\arm64-v8a\\libncore.so"),
    (Join-Path $repoRoot "build\\android\\obj\\local\\arm64-v8a\\libncore.so"),
    (Join-Path $repoRoot "build\\obj\\local\\arm64-v8a\\libncore.so")
)

$sourcePath = $env:NOOK_EMBEDDED_NCORE_SOURCE
if (-not [string]::IsNullOrWhiteSpace($sourcePath)) {
    if (-not (Test-Path $sourcePath)) {
        throw "NOOK_EMBEDDED_NCORE_SOURCE not found at $sourcePath"
    }
} else {
    $sourcePath = $null
    $existingCandidates = @($candidateSources | Where-Object { Test-Path $_ })
    if ($existingCandidates.Count -eq 0) {
        throw "libncore.so not found. Build nook_ncore first or set NOOK_EMBEDDED_NCORE_SOURCE."
    }

    $candidateMetadata = @()
    foreach ($candidate in $existingCandidates) {
        $item = Get-Item $candidate
        $candidateMetadata += [PSCustomObject]@{
            Path = $candidate
            LastWriteTimeUtc = $item.LastWriteTimeUtc
            Length = $item.Length
            Hash = (Get-FileHash $candidate -Algorithm MD5).Hash
        }
    }

    $distinctHashes = @($candidateMetadata.Hash | Select-Object -Unique)
    if ($distinctHashes.Count -gt 1) {
        Write-Warning "Multiple libncore.so candidates differ; selecting the most recently built artifact."
        foreach ($candidate in $candidateMetadata | Sort-Object LastWriteTimeUtc -Descending) {
            Write-Warning ("  candidate={0} utc={1:o} size={2} md5={3}" -f
                $candidate.Path,
                $candidate.LastWriteTimeUtc,
                $candidate.Length,
                $candidate.Hash)
        }
    }

    $priorityPrefixes = @(
        (Join-Path $repoRoot "libs\\arm64-v8a").ToLowerInvariant(),
        (Join-Path $repoRoot "build\\libs\\arm64-v8a").ToLowerInvariant(),
        (Join-Path $repoRoot "build\\single-server-package\\arm64-v8a").ToLowerInvariant(),
        (Join-Path $repoRoot "build\\single-server-staging\\arm64-v8a").ToLowerInvariant(),
        (Join-Path $repoRoot "obj\\local\\arm64-v8a").ToLowerInvariant(),
        (Join-Path $repoRoot "build\\android\\libs\\arm64-v8a").ToLowerInvariant(),
        (Join-Path $repoRoot "build\\android\\obj\\local\\arm64-v8a").ToLowerInvariant(),
        (Join-Path $repoRoot "build\\obj\\local\\arm64-v8a").ToLowerInvariant()
    )

    $preferredCandidate = $null
    foreach ($prefix in $priorityPrefixes) {
        $preferredCandidate = $candidateMetadata | Where-Object {
            $_.Path.ToLowerInvariant().StartsWith($prefix)
        } | Sort-Object @{ Expression = 'LastWriteTimeUtc'; Descending = $true },
                        @{ Expression = 'Length'; Descending = $true } |
            Select-Object -First 1
        if ($null -ne $preferredCandidate) {
            break
        }
    }

    if ($null -ne $preferredCandidate) {
        $sourcePath = $preferredCandidate.Path
    } else {
        $sourcePath = ($candidateMetadata |
            Sort-Object @{ Expression = 'LastWriteTimeUtc'; Descending = $true },
                        @{ Expression = 'Length'; Descending = $true } |
            Select-Object -First 1).Path
    }
    if ($null -eq $sourcePath) {
        throw "libncore.so not found. Build nook_ncore first or set NOOK_EMBEDDED_NCORE_SOURCE."
    }
}

New-Item -ItemType Directory -Force (Split-Path -Parent $headerPath) | Out-Null

$sourceItem = Get-Item $sourcePath
$sourceHash = (Get-FileHash $sourcePath -Algorithm SHA256).Hash.ToLowerInvariant()
$sourceName = Split-Path -Leaf $sourcePath
$bytes = [System.IO.File]::ReadAllBytes($sourcePath)
$tempHeaderPath = "$headerPath.tmp"
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("#pragma once")
$lines.Add("")
$lines.Add("// Auto-generated by tools/build_embedded_ncore_blob.ps1. Do not edit manually.")
$lines.Add("")
$lines.Add("namespace nook {")
$lines.Add("namespace server {")
$lines.Add("")
$lines.Add("#if defined(NOOK_DEFINE_EMBEDDED_NCORE_BLOB)")
$lines.Add("extern const unsigned char kNookEmbeddedNcoreBlob[] = {")

for ($i = 0; $i -lt $bytes.Length; $i += 12) {
    $chunk = $bytes[$i..([Math]::Min($i + 11, $bytes.Length - 1))]
    $formatted = ($chunk | ForEach-Object { ('0x{0:x2}' -f $_) }) -join ", "
    if ($i + 12 -lt $bytes.Length) {
        $lines.Add("    $formatted,")
    } else {
        $lines.Add("    $formatted")
    }
}

$lines.Add("};")
$lines.Add("#else")
$lines.Add("extern const unsigned char kNookEmbeddedNcoreBlob[];")
$lines.Add("#endif")
$lines.Add("")
$lines.Add("static constexpr unsigned int kNookEmbeddedNcoreBlobSize = " + $bytes.Length + "u;")
$lines.Add('static constexpr const char* kNookEmbeddedNcoreSourcePath = "' +
    (($sourceName -replace '\\', '\\') -replace '"', '\"') + '";')
$lines.Add('static constexpr const char* kNookEmbeddedNcoreSourceSha256 = "' + $sourceHash + '";')
$lines.Add("static constexpr unsigned int kNookEmbeddedNcoreSourceFileSize = " + $sourceItem.Length + "u;")
$lines.Add('static constexpr const char* kNookEmbeddedNcoreSourceLastWriteUtc = "";')
$lines.Add("")
$lines.Add("}  // namespace server")
$lines.Add("}  // namespace nook")

[System.IO.File]::WriteAllLines($tempHeaderPath, $lines, [System.Text.Encoding]::ASCII)
$newHeaderBytes = [System.IO.File]::ReadAllBytes($tempHeaderPath)
$shouldReplace = $true
if (Test-Path $headerPath) {
    $existingHeaderBytes = [System.IO.File]::ReadAllBytes($headerPath)
    if ($existingHeaderBytes.Length -eq $newHeaderBytes.Length) {
        $shouldReplace = $false
        for ($index = 0; $index -lt $existingHeaderBytes.Length; ++$index) {
            if ($existingHeaderBytes[$index] -ne $newHeaderBytes[$index]) {
                $shouldReplace = $true
                break
            }
        }
    }
}

if ($shouldReplace) {
    $lastError = $null
    $replaced = $false
    for ($attempt = 1; $attempt -le 8; ++$attempt) {
        try {
            [System.IO.File]::Copy($tempHeaderPath, $headerPath, $true)
            $replaced = $true
            break
        } catch {
            $lastError = $_
            Start-Sleep -Milliseconds (150 * $attempt)
        }
    }
    if (-not $replaced) {
        throw "failed to replace $headerPath after retries; ensure blob refresh and nook-server build are serialized. last_error=$lastError"
    }
}

Remove-Item -LiteralPath $tempHeaderPath -Force -ErrorAction SilentlyContinue
Write-Output "generated: $headerPath"
Write-Output "source: $sourcePath"
Write-Output "source_sha256: $sourceHash"
Write-Output "source_size: $($sourceItem.Length)"
