$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$javaHome = $env:JAVA_HOME
if ([string]::IsNullOrWhiteSpace($javaHome)) {
    throw "JAVA_HOME is not set"
}

$javac = Join-Path $javaHome "bin\\javac.exe"
if (-not (Test-Path $javac)) {
    throw "javac not found at $javac"
}

$jarTool = Join-Path $javaHome "bin\\jar.exe"
if (-not (Test-Path $jarTool)) {
    throw "jar not found at $jarTool"
}

$d8 = "E:\\SDK\\build-tools\\34.0.0\\d8.bat"
if (-not (Test-Path $d8)) {
    throw "d8 not found at $d8"
}

$sourceFile = Join-Path $repoRoot "src\\java_helper\\nook\\java\\NookJsInvocationHandler.java"
$buildRoot = Join-Path $repoRoot "build\\register_class_helper"
$classesDir = Join-Path $buildRoot "classes"
$dexDir = Join-Path $buildRoot "dex"
$jarPath = Join-Path $buildRoot "nook_register_class_helper.jar"
$headerPath = Join-Path $repoRoot "src\\agent_runtime\\generated\\nook_register_class_helper_dex.h"

New-Item -ItemType Directory -Force $classesDir | Out-Null
New-Item -ItemType Directory -Force $dexDir | Out-Null
New-Item -ItemType Directory -Force (Split-Path -Parent $headerPath) | Out-Null

Remove-Item -Recurse -Force (Join-Path $classesDir "*") -ErrorAction SilentlyContinue
Remove-Item -Recurse -Force (Join-Path $dexDir "*") -ErrorAction SilentlyContinue
Remove-Item -Force $jarPath -ErrorAction SilentlyContinue

& $javac --release 8 -d $classesDir $sourceFile
if ($LASTEXITCODE -ne 0) {
    throw "javac failed with exit code $LASTEXITCODE"
}

Push-Location $classesDir
try {
    & $jarTool --create --file $jarPath .
    if ($LASTEXITCODE -ne 0) {
        throw "jar failed with exit code $LASTEXITCODE"
    }
} finally {
    Pop-Location
}

& $d8 --min-api 26 --output $dexDir $jarPath
if ($LASTEXITCODE -ne 0) {
    throw "d8 failed with exit code $LASTEXITCODE"
}

$dexPath = Join-Path $dexDir "classes.dex"
if (-not (Test-Path $dexPath)) {
    throw "generated dex not found at $dexPath"
}

$bytes = [System.IO.File]::ReadAllBytes($dexPath)
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("#pragma once")
$lines.Add("")
$lines.Add("// Auto-generated by tools/build_register_class_helper.ps1. Do not edit manually.")
$lines.Add("")
$lines.Add("namespace nook {")
$lines.Add("namespace agent_runtime {")
$lines.Add("")
$lines.Add("static const unsigned char kNookRegisterClassHelperDex[] = {")

for ($i = 0; $i -lt $bytes.Length; $i += 12) {
    $chunk = $bytes[$i..([Math]::Min($i + 11, $bytes.Length - 1))]
    $formatted = ($chunk | ForEach-Object { ('0x{0:x2}' -f $_) }) -join ", "
    if ($i + 12 -lt $bytes.Length) {
        $lines.Add("    $formatted,")
    } else {
        $lines.Add("    $formatted")
    }
}

$lines.Add("};")
$lines.Add("")
$lines.Add("static constexpr unsigned int kNookRegisterClassHelperDexSize = " + $bytes.Length + "u;")
$lines.Add("")
$lines.Add("}  // namespace agent_runtime")
$lines.Add("}  // namespace nook")

[System.IO.File]::WriteAllLines($headerPath, $lines, [System.Text.Encoding]::ASCII)
Write-Output "generated: $headerPath"
